name: Flutter Build APK

on:
  push:
    branches: [ "main" ] # سيعمل البناء تلقائياً عند كل عملية رفع كود للفرع الرئيسي

jobs:
  build:
    runs-on: ubuntu-latest # استخدام نظام لينكس للبناء

    steps:
      - uses: actions/checkout@v3 # سحب الكود من المستودع

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # فلاتر تحتاج جافا للبناء

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # استخدام النسخة المستقرة من فلاتر

      - name: Get dependencies
        run: flutter pub get # تحميل المكتبات

      - name: Build APK
        run: flutter build apk --release # أمر بناء التطبيق

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk # مكان ملف الـ APK الناتج
